"""updated note to notes

Revision ID: 043961051c6f
Revises: 
Create Date: 2024-12-28 21:37:56.525108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043961051c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=256), nullable=True))
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
