"""solving sqlalchemy warning

Revision ID: 0b60fc151bf1
Revises: 1b6a48ab92e0
Create Date: 2024-12-31 19:10:25.049623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b60fc151bf1'
down_revision = '1b6a48ab92e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.alter_column('easiness',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.alter_column('easiness',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
