"""updated date attribute for DailyWord again

Revision ID: 855b36dfdea9
Revises: ff94e1e66345
Create Date: 2025-01-06 10:20:33.662570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855b36dfdea9'
down_revision = 'ff94e1e66345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_words', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_words', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
