"""introduced UserQuestion model

Revision ID: 950e1885c46a
Revises: ede84d094104
Create Date: 2024-12-31 16:14:27.008214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950e1885c46a'
down_revision = 'ede84d094104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('easiness')
        batch_op.drop_column('date')
        batch_op.drop_column('interval')
        batch_op.drop_column('repetitions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repetitions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('easiness', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
