"""changed default value for options attribute

Revision ID: d6f5ca14364c
Revises: 950e1885c46a
Create Date: 2024-12-31 16:32:59.373880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f5ca14364c'
down_revision = '950e1885c46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
