"""created lessonType attribute for Lesson model

Revision ID: ede84d094104
Revises: 043961051c6f
Create Date: 2024-12-29 11:46:19.518392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede84d094104'
down_revision = '043961051c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessonType', sa.String(length=32)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('lessonType')

    # ### end Alembic commands ###
